name: Dogfood

on: workflow_dispatch

permissions: {}

jobs:
  upterm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - name: Start upterm session
        uses: ./
        with:
          limit-access-to-actor: true
